# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CadPosT.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_curso(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMenu = QtWidgets.QFrame(self.top)
        self.btnMenu.setMaximumSize(QtCore.QSize(120, 50))
        self.btnMenu.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.btnMenu.setFrameShape(QtWidgets.QFrame.Box)
        self.btnMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnMenu.setObjectName("btnMenu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.btnMenu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_Menu = QtWidgets.QPushButton(self.btnMenu)
        self.pushButton_Menu.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_Menu.setStyleSheet("QPushButton{\n"
"border-radius: 8px;\n"
"font: 87 8pt \"Arial Black\";\n"
"color: white;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Menu.setIcon(icon)
        self.pushButton_Menu.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Menu.setObjectName("pushButton_Menu")
        self.verticalLayout_5.addWidget(self.pushButton_Menu)
        self.horizontalLayout_2.addWidget(self.btnMenu)
        self.menutop = QtWidgets.QFrame(self.top)
        self.menutop.setMinimumSize(QtCore.QSize(0, 50))
        self.menutop.setMaximumSize(QtCore.QSize(16777215, 50))
        self.menutop.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.menutop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menutop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menutop.setObjectName("menutop")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.menutop)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_11 = QtWidgets.QFrame(self.menutop)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_10.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.menutop)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label = QtWidgets.QLabel(self.frame_12)
        self.label.setGeometry(QtCore.QRect(60, 0, 151, 51))
        self.label.setStyleSheet("background-image: url(:/img/img/LogoP.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.menutop)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_23 = QtWidgets.QFrame(self.frame_13)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_17.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_13)
        self.frame_24.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_Reca = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_Reca.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/recaregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Reca.setIcon(icon1)
        self.pushButton_Reca.setObjectName("pushButton_Reca")
        self.horizontalLayout_16.addWidget(self.pushButton_Reca)
        self.pushButton_logado = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_logado.setMinimumSize(QtCore.QSize(75, 30))
        self.pushButton_logado.setStyleSheet("color: white;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/userLogado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logado.setIcon(icon2)
        self.pushButton_logado.setObjectName("pushButton_logado")
        self.horizontalLayout_16.addWidget(self.pushButton_logado)
        self.pushButton_Sair = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_Sair.setStyleSheet("color: white;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/sair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sair.setIcon(icon3)
        self.pushButton_Sair.setObjectName("pushButton_Sair")
        self.horizontalLayout_16.addWidget(self.pushButton_Sair)
        self.horizontalLayout_17.addWidget(self.frame_24)
        self.horizontalLayout_10.addWidget(self.frame_13)
        self.horizontalLayout_2.addWidget(self.menutop)
        self.verticalLayout.addWidget(self.top)
        self.Conteudo = QtWidgets.QFrame(self.centralwidget)
        self.Conteudo.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.Conteudo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Conteudo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Conteudo.setObjectName("Conteudo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Conteudo)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(self.Conteudo)
        self.menu.setMinimumSize(QtCore.QSize(120, 0))
        self.menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menu.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.pushButton_Home = QtWidgets.QPushButton(self.menu)
        self.pushButton_Home.setGeometry(QtCore.QRect(10, 0, 100, 30))
        self.pushButton_Home.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Home.setStyleSheet("QPushButton{\n"
"border-radius: 8px;\n"
"font: 87 8pt \"Arial Black\";\n"
"color: white;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43,43,43);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Home.setIcon(icon4)
        self.pushButton_Home.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton_User = QtWidgets.QPushButton(self.menu)
        self.pushButton_User.setGeometry(QtCore.QRect(10, 40, 100, 30))
        self.pushButton_User.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_User.setStyleSheet("QPushButton{\n"
"border-radius: 8px;\n"
"font: 87 8pt \"Arial Black\";\n"
"color: white;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43,43,43);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/img/userInfo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_User.setIcon(icon5)
        self.pushButton_User.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_User.setObjectName("pushButton_User")
        self.pushButton_Unidade = QtWidgets.QPushButton(self.menu)
        self.pushButton_Unidade.setGeometry(QtCore.QRect(10, 80, 100, 30))
        self.pushButton_Unidade.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Unidade.setStyleSheet("QPushButton{\n"
"border-radius: 8px;\n"
"font: 87 8pt \"Arial Black\";\n"
"color: white;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43,43,43);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/img/Unidades.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Unidade.setIcon(icon6)
        self.pushButton_Unidade.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Unidade.setObjectName("pushButton_Unidade")
        self.pushButton_Curso = QtWidgets.QPushButton(self.menu)
        self.pushButton_Curso.setGeometry(QtCore.QRect(10, 120, 100, 30))
        self.pushButton_Curso.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Curso.setStyleSheet("QPushButton{\n"
"border-radius: 8px;\n"
"font: 87 8pt \"Arial Black\";\n"
"color: white;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43,43,43);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/img/PostoTrabalho.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Curso.setIcon(icon7)
        self.pushButton_Curso.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Curso.setObjectName("pushButton_Curso")
        self.pushButton_Atividade = QtWidgets.QPushButton(self.menu)
        self.pushButton_Atividade.setGeometry(QtCore.QRect(10, 160, 100, 30))
        self.pushButton_Atividade.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Atividade.setStyleSheet("QPushButton{\n"
"border-radius: 8px;\n"
"font: 87 8pt \"Arial Black\";\n"
"color: white;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43,43,43);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/img/Atividade.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Atividade.setIcon(icon8)
        self.pushButton_Atividade.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Atividade.setObjectName("pushButton_Atividade")
        self.horizontalLayout.addWidget(self.menu)
        self.conte = QtWidgets.QFrame(self.Conteudo)
        self.conte.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.conte.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.conte.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conte.setObjectName("conte")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.conte)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.conte)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_21 = QtWidgets.QFrame(self.frame_6)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_21)
        self.frame_16.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_16.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_14.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_21)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_13.addWidget(self.frame_19)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Area = QtWidgets.QLabel(self.frame_17)
        self.label_Area.setMinimumSize(QtCore.QSize(30, 0))
        self.label_Area.setMaximumSize(QtCore.QSize(40, 20))
        self.label_Area.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(43, 43, 43);\n"
"font: 87 8pt \"Arial Black\";\n"
"")
        self.label_Area.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Area.setObjectName("label_Area")
        self.verticalLayout_3.addWidget(self.label_Area)
        self.lineEdit_Area = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_Area.setMinimumSize(QtCore.QSize(180, 25))
        self.lineEdit_Area.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_Area.setStyleSheet("QLineEdit{\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 2px;\n"
"padding: 0px 10px;\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border: 1px solid  rgb(33, 122, 255);\n"
"}")
        self.lineEdit_Area.setObjectName("lineEdit_Area")
        self.verticalLayout_3.addWidget(self.lineEdit_Area)
        self.horizontalLayout_13.addLayout(self.verticalLayout_3)
        self.frame_20 = QtWidgets.QFrame(self.frame_17)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13.addWidget(self.frame_20)
        self.horizontalLayout_14.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_21)
        self.frame_18.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_14.addWidget(self.frame_18)
        self.verticalLayout_11.addWidget(self.frame_21)
        self.frame_15 = QtWidgets.QFrame(self.frame_6)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_22 = QtWidgets.QFrame(self.frame_15)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_15.addWidget(self.frame_22)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, 9, -1)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_Cad = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_Cad.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButton_Cad.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_Cad.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(97, 97, 97);\n"
"text-align: center;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(43, 43, 43);\n"
"    \n"
"}")
        self.pushButton_Cad.setObjectName("pushButton_Cad")
        self.horizontalLayout_12.addWidget(self.pushButton_Cad)
        self.pushButton_Atual = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_Atual.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButton_Atual.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_Atual.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(97, 97, 97);\n"
"text-align: center;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(43, 43, 43);\n"
"    \n"
"}")
        self.pushButton_Atual.setObjectName("pushButton_Atual")
        self.horizontalLayout_12.addWidget(self.pushButton_Atual)
        self.pushButton_cancelar = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_cancelar.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButton_cancelar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_cancelar.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(97, 97, 97);\n"
"text-align: center;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(43, 43, 43);\n"
"    \n"
"}")
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")
        self.horizontalLayout_12.addWidget(self.pushButton_cancelar)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_12)
        self.verticalLayout_11.addWidget(self.frame_15)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_7)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_Deletar = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_Deletar.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButton_Deletar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_Deletar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(97, 97, 97);\n"
"text-align: center;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(43, 43, 43);\n"
"    \n"
"}")
        self.pushButton_Deletar.setObjectName("pushButton_Deletar")
        self.horizontalLayout_11.addWidget(self.pushButton_Deletar)
        self.frame_14 = QtWidgets.QFrame(self.frame_3)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Quantidade = QtWidgets.QLabel(self.frame_14)
        self.label_Quantidade.setMinimumSize(QtCore.QSize(100, 25))
        self.label_Quantidade.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(43, 43, 43);\n"
"font: 87 8pt \"Arial Black\";\n"
"border-radius: 5px;\n"
"")
        self.label_Quantidade.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Quantidade.setObjectName("label_Quantidade")
        self.verticalLayout_4.addWidget(self.label_Quantidade)
        self.horizontalLayout_11.addWidget(self.frame_14)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9.addWidget(self.frame_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_Pesquisa = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_Pesquisa.setMinimumSize(QtCore.QSize(160, 25))
        self.lineEdit_Pesquisa.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_Pesquisa.setStyleSheet("QLineEdit{\n"
"background-color: rgb(216, 216, 216);\n"
"border-radius: 2px;\n"
"padding: 0px 10px;\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border: 1px solid  rgb(33, 122, 255);\n"
"}")
        self.lineEdit_Pesquisa.setObjectName("lineEdit_Pesquisa")
        self.horizontalLayout_8.addWidget(self.lineEdit_Pesquisa)
        self.pushButton_Pes = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_Pes.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButton_Pes.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_Pes.setStyleSheet("QPushButton{\n"
"background-image: url(:/img/img/pesqui.png);\n"
"background-position:right;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(97, 97, 97);\n"
"text-align: center;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(43, 43, 43);\n"
"    \n"
"}")
        self.pushButton_Pes.setObjectName("pushButton_Pes")
        self.horizontalLayout_8.addWidget(self.pushButton_Pes)
        self.pushButton_Todos = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_Todos.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton_Todos.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_Todos.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(97, 97, 97);\n"
"text-align: center;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(43, 43, 43);\n"
"    \n"
"}")
        self.pushButton_Todos.setObjectName("pushButton_Todos")
        self.horizontalLayout_8.addWidget(self.pushButton_Todos)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.verticalLayout_11.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_11.addWidget(self.frame_8)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.conte)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.verticalLayout_13.addWidget(self.tableWidget)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.conte)
        self.verticalLayout.addWidget(self.Conteudo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Menu.setText(_translate("MainWindow", "Menu"))
        self.pushButton_logado.setText(_translate("MainWindow", "Admin"))
        self.pushButton_Sair.setText(_translate("MainWindow", "Sair"))
        self.pushButton_Home.setText(_translate("MainWindow", " Home"))
        self.pushButton_User.setText(_translate("MainWindow", " User"))
        self.pushButton_Unidade.setText(_translate("MainWindow", " Unidade"))
        self.pushButton_Curso.setText(_translate("MainWindow", "Curso"))
        self.pushButton_Atividade.setText(_translate("MainWindow", " Atividade"))
        self.label_Area.setText(_translate("MainWindow", "Area"))
        self.lineEdit_Area.setPlaceholderText(_translate("MainWindow", "Area"))
        self.pushButton_Cad.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButton_Atual.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.pushButton_Deletar.setText(_translate("MainWindow", "Deletar"))
        self.label_Quantidade.setText(_translate("MainWindow", "Quantidade: 0"))
        self.lineEdit_Pesquisa.setPlaceholderText(_translate("MainWindow", "Area"))
        self.pushButton_Pes.setText(_translate("MainWindow", "Pesquisar"))
        self.pushButton_Todos.setText(_translate("MainWindow", "Todos"))
import template.Principal_img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_curso()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
