# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 630)
        MainWindow.setMinimumSize(QtCore.QSize(200, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top = QtWidgets.QFrame(self.centralwidget)
        self.Top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Top.setStyleSheet("background-color: rgb(23, 23, 23);")
        self.Top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top.setObjectName("Top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Top)
        self.horizontalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.Top)
        self.mid = QtWidgets.QFrame(self.centralwidget)
        self.mid.setStyleSheet("QFrame{\n"
"\n"
"    background-image: url(:/img/img/sumare.png);\n"
"background-size: 100% 100%;\n"
"background-repeat: no-repeat;\n"
"}\n"
"")
        self.mid.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid.setObjectName("mid")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mid)
        self.horizontalLayout.setContentsMargins(9, 20, 9, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login = QtWidgets.QFrame(self.mid)
        self.login.setMaximumSize(QtCore.QSize(500, 500))
        self.login.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"background-image: url();\n"
"border-radius: 5px;")
        self.login.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login.setObjectName("login")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.login)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QFrame(self.login)
        self.logo.setMaximumSize(QtCore.QSize(16777215, 100))
        self.logo.setStyleSheet("\n"
"background-color: rgb(53, 63, 83);")
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.logo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.logo)
        self.label_4.setStyleSheet("background-image: url(:/img/img/Logo.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-size: auto;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addWidget(self.logo)
        self.frame = QtWidgets.QFrame(self.login)
        self.frame.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setStyleSheet("background-image: url(:/img/img/login3.png);\n"
"\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-size: auto;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_login = QtWidgets.QLabel(self.frame_4)
        self.label_login.setMinimumSize(QtCore.QSize(50, 30))
        self.label_login.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"color: rgb(0,0,0);\n"
"font-weight: bold;\n"
"border: 1px solid rgb(0,0,0);\n"
"")
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_login.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_login.setStyleSheet("QLineEdit{\n"
"border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 1px solid black;\n"
"padding: 0px 10px;\n"
"}\n"
"QLineEdit:hover{\n"
"border: 1px solid  rgb(33, 122, 255);\n"
"}\n"
"QLineEdit:pressed{\n"
"padding: 0px 10px;\n"
"border: 1px solid blue;\n"
"}")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_login)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_senha = QtWidgets.QLabel(self.frame_4)
        self.label_senha.setMinimumSize(QtCore.QSize(50, 30))
        self.label_senha.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"color: rgb(0,0,0);\n"
"font-weight: bold;\n"
"border: 1px solid rgb(0,0,0);")
        self.label_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_senha.setObjectName("label_senha")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_senha)
        self.lineEdit_senha = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_senha.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_senha.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_senha.setStyleSheet("QLineEdit{\n"
"border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 1px solid black;\n"
"padding: 0px 10px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 1px solid black;\n"
"padding: 0px 10px;\n"
"}\n"
"QLineEdit:hover{\n"
"border: 1px solid  rgb(33, 122, 255);\n"
"}\n"
"QLineEdit:pressed{\n"
"padding: 0px 10px;\n"
"border: 1px solid blue;\n"
"}\n"
"\n"
"QLineEdit:pressed{\n"
"\n"
"border: 1px solid blue;\n"
"padding: 0px 10px;\n"
"}")
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_senha)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_Esqueceu = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_Esqueceu.setStyleSheet("QPushButton{\n"
"\n"
"color: rgb(43,43,43);\n"
"font: 87 8pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0,0,0);\n"
"}\n"
"")
        self.pushButton_Esqueceu.setObjectName("pushButton_Esqueceu")
        self.verticalLayout_9.addWidget(self.pushButton_Esqueceu)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.login)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_Entrar = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_Entrar.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_Entrar.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(53, 63, 83);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(70, 81, 115);\n"
"    \n"
"}")
        self.pushButton_Entrar.setObjectName("pushButton_Entrar")
        self.verticalLayout_4.addWidget(self.pushButton_Entrar)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.login)
        self.verticalLayout.addWidget(self.mid)
        self.bot = QtWidgets.QFrame(self.centralwidget)
        self.bot.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bot.setStyleSheet("background-color: rgb(23, 23, 23);")
        self.bot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bot.setObjectName("bot")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bot)
        self.horizontalLayout_5.setContentsMargins(0, 20, 5, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.bot)
        self.label_2.setStyleSheet("background-color: rgb(23, 23, 23);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.bot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_login.setText(_translate("MainWindow", "Login"))
        self.label_senha.setText(_translate("MainWindow", "Senha"))
        self.pushButton_Esqueceu.setText(_translate("MainWindow", "Esqueceu a senha?"))
        self.pushButton_Entrar.setText(_translate("MainWindow", "Entrar"))
        self.label_2.setText(_translate("MainWindow", "Create by Alann"))
import template.Login_img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
